version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestP6Project
  gitServerName: rlakshitha0912
  gitUrl: https://github.com/rlakshitha0912
  gitUsername: rlakshitha0912
  gitBranch: main
- name: TestAdapaterPackage
  version: "1.0"
  gitServerName: rlakshitha0912
  gitUrl: https://github.com/rlakshitha0912
  gitUsername: rlakshitha0912
  gitBranch: main
services:
- serviceName: project.testp6.integrations:test
  packages:
  - name: TestP6Project
    version: "1.0"
  - name: TestAdapaterPackage
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1115
- serviceName: service:date
  packages:
  - name: TestAdapaterPackage
    version: "1.0"
